"""init schema

Revision ID: 53c15087efaf
Revises: 
Create Date: 2026-01-13 16:00:48.997794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c15087efaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_migration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_person_id', sa.String(), nullable=True),
    sa.Column('old_person_bdrc_id', sa.String(), nullable=True),
    sa.Column('new_person_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_migration')
    # ### end Alembic commands ###
